spring:
  application:
    name: book-search

  datasource:
    url: jdbc:postgresql://localhost:5432/bookdb
    username: bookuser
    password: bookpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /v3/api-docs